### ISSUE TITLE
Tarefa: Levantar lista de possíveis palestrantes acadêmicos

### ISSUE THREAD

**Issue by JPTIZ** [seccom-ufsc/reunioes#1]
Informações
---

Speakerfights:
- Palestras: https://speakerfight.com/events/seccom-2019-palestras/
- Minicursos: https://speakerfight.com/events/seccom-2019-minicursos/

Programação:
- Geral: [Google Spreadsheets](https://docs.google.com/spreadsheets/d/1U_lRkZlp1PWaqAVPkdmxQygapAM8f2UH6FedAEp36XA/edit#gid=0).

Checklist
---

- [x] (7/8) Convidar ~9~ palestrantes para keynotes (alterado para 8 pelo cancelamento da quarta-feira à tarde);
- [x] (6/5) Levantar pelo menos 8 nomes para CCO (8 espaços para palestra):
- [x] (3/3) Levantar pelo menos 3 nomes para SIN (3 espaços para palestra).

Keynotes
---

### Confirmados

| # | Nome                   | Descrição | Foto | Preferência/Restrições de Horário |
| - | ---------------------- | --------- | ---- | --------------------------------- |
| 1 | John "Maddog" Hall     | ✔         | ✔    |                                   |
| 2 | Mário Sérgio Queiroz   | ✔          | ✔     | Nenhuma                                 |
| 3 | Victor A. de Menezes   | ✔         | ✔    |                                   |
| 4 | Álvaro Justen          |           |      | Preferência: dia 30/09                                 |
| 5 | Melissa Weber Mendonça | ✔         | ✔    |                                   |
| 6 | Maria Queiroz          | ✔         | ✔    |                                   |
| 7 | Taíssa Vasconcelos     | ✔         | ✔    | 03/10 à noite                                 |
| 8 |                        |           |      |                                   |

- **John "Maddog" Hall**
  - Tema sugerido: potencialização da indústria nacional
<br>

- **Mário Sérgio Queiroz**
  - Tema sugerido: inclusão na áreas de SIN/CCO
<br>

- **Victor Menezes**
  - Tema sugerido: segurança de dados
<br>

- **Álvaro Justen** (a.k.a. "Turicas")
  - Tema sugerido: dados públicos e brasil.io
  - **Exige custeio para permanência**
<br>

- **Melissa Weber Mendonça**
  - Tema sugerido: computação científica
  - **Foco para CCO**
<br>

- **Maria Queiroz**
  - Tema sugerido: uso de dados para impacto social
<br>

- **Taíssa Vasconcelos**
  - Tema sugerido: Empatia organizacional, mulheres na tecnologia
<br>

### Aguardando confirmação

- **Jéssica Temporal**
  - Tema sugerido: ?
<br>

- **João Candido Dovicchi**
  - Tema sugerido: ?
  - **Foco para CCO**
<br>

- **Equipe RocketChat**
  - Tema sugerido: gerenciamento de projetos open-source no mercado
  - **Foco para SIN**
<br>

- **Paulo Torrens**
  - Tema sugerido: algo que dê uma visão crítica sobre linguagens de programação
  - **Foco para CCO**
<br>

### Não contatados

<br>

## Professores para palestrar

- Marcio Castro;
- Carina Friedrich;
- Lucas Nicolao (FSC);
- Jean Hauck.

### Confirmados/Com interesse

| Nome                       | Título | Descrição | Restrição                                                                                         | Preferência                      |
| -------------------------- | ------ | --------- | ------------------------------------------------------------------------------------------------- | -------------------------------- |
| Jean Hauck                 | ✔      | ✔         | Nenhuma                                                                                           | 30/09 ou 01/10 às 20h20          |
| Lucas Zacchi               | ✔      | ✔         | Nenhuma                                                                                           | Nenhuma                          |
| Raul Wazlawick             | ✔      | ✔         | Nenhuma                                                                                           | Nenhuma                          |
| Odorico Machado Mendizabal | ✔      | ✔         | **Não pode:** Quarta das 16h30 às 17h30                                                            | Durante o dia (para atingir CCO) |
| Lucas Nicolao              | ✔      | ✔         | **Não pode:** 2ª à tarde, 3ª até 15h, 6ª à tarde | Nenhuma |
| Márcio Castro              | ✔      | ✔         | **Só Pode**: Terça-feira das 13h30 às 16h30 e outros dias de manhã. **Não pode**: Quinta e Sexta. | Terça-feira, início da tarde     |
| Carina Friedrich           |        |           |                                                                                                   |                                  |
| Maicon Rafael Zatelli      | ✔      | ✔         | Nenhuma (de manhã e de noite, então...)                                                           | Quarta-feira início da tarde.    |

### Em análise

| Nome                        | Título | Descrição | Restrição           | Preferência | Enviado        |
| --------------------------- | ------ | --------- | ------------------- | ----------- | -------------- |
| Roberta Lingnau de Oliveira | ✔      | ✔         | **Não pode** Quarta | Nenhuma     | 03 de Setembro |
| Guilherme Hayashi           | ✔      | ✔         | Depende do dia      | Nenhuma     | 06 de Setembro |
| Gabriel Baldessar           | ✔      | ✔         | Nenhuma             | Nenhuma     | 21 de Maio     |
| José De Lucca | ✔      | ✔         |  ? | ? | - |

### Sem resposta

| Nome          | Último contato |
| ------------- | -------------- |

**Comment by cauebs** [comment]
Como são 9 keynotes ao total, seria bacana tentar conseguir pelo menos 5 mulheres (e distribuir isso nos dois períodos). É um objetivo comum em eventos de Python e outras conferências de comunidades inclusivas.

**Comment by junakayama** [comment]
Dúvida: o que significa a diferença de nomes pra CCO e nomes pra SIN? Somente o horário ou os assuntos de interesse também?

**Comment by JPTIZ** [comment]
> Dúvida: o que significa a diferença de nomes pra CCO e nomes pra SIN? Somente o horário ou os assuntos de interesse também?

Tanto horário quanto assuntos de interesse (vide [tabela de horários](https://docs.google.com/spreadsheets/d/1U_lRkZlp1PWaqAVPkdmxQygapAM8f2UH6FedAEp36XA/edit#gid=0)), pra gente direcionar bem o assunto pro público (já que sistemas, por exemplo, costuma não ter horário livre à tarde, aí fica reservada a noite pra eles).

**Comment by cauebs** [comment]
Tava olhando a checklist agora e não entendi uma coisa. Achei que a ideia das palestras era abrir um _call for papers_ e deixar o público escolher. Por que precisaríamos levantar nomes?

**Comment by JPTIZ** [comment]
> Tava olhando a checklist agora e não entendi uma coisa. Achei que a ideia das palestras era abrir um _call for papers_ e deixar o público escolher. Por que precisaríamos levantar nomes?

Hum, tinha esquecido dessa parte do _call for papers_, to acostumado com as SECCOMs passadas. Ainda assim acho que seria interessante ir atrás de palestrantes, não sei o quanto conseguiríamos divulgar tão longe.

Se vamos fazer o _call_, então adiciono uma task de fazer um formulário pra submissão de palestra? Aí podemos começar divulgando para os professores do departamento (e onde mais tivermos contato que possa trazer palestras legais).

**Comment by cauebs** [comment]
Pra isso tem o [Speakerfight](https://speakerfight.com/):

![Screenshot_2019-05-01 Speakerfight - New Event](https://user-images.githubusercontent.com/6764500/57032089-e0094280-6c1f-11e9-81ff-0b966431cd44.png)

**Comment by cauebs** [comment]
[Exemplo de evento (Caipyra 2019)](https://speakerfight.com/events/caipyra-2019-palestras/)

**Comment by cauebs** [comment]
Enviei email pro [Maddog](https://en.wikipedia.org/wiki/Jon_Hall_%28programmer%29), ele disse que vai dar resposta em uns dois ou três dias :)

A Vanessa sugeriu que a gente convidasse o @sergiomario pra falar sobre as dificuldades de promover a inclusão em comunidades de tecnologia. Ele tem muita competência pra falar disso. Deem um :+1: aí que eu convido ele.

**Comment by cauebs** [comment]
Ok, temos confirmação do Mário ;)

**Comment by cauebs** [comment]
Pensando em convidar o Roberto Ierusalimschy, um dos criadores da linguagem de programação Lua, por ser um projeto brasileiro de relevância internacional. Aqui tem algumas das palestras dele: http://www.inf.puc-rio.br/~roberto/talks/index.html (também podem dar uma olhada no YouTube, se quiserem). Aguardo os :+1:

**Comment by cauebs** [comment]
Também pensei na equipe do RocketChat, uma alternativa ao Slack completamente open source e produzida em Porto Alegre. Algum deles poderia vir falar sobre a viabilidade de modelos de negócios com software livre.

**Comment by Coquinho** [comment]
Gostei de todos os nomes Cauê

**Comment by junakayama** [comment]
Pensei na [Maria Queiroz](https://www.linkedin.com/in/maria-queiroz/), ela é analista de BI, está por dentro do movimento negro e lgbt e tem experiência com palestras.

**Comment by JPTIZ** [comment]
Aleatoriamente me deparei com [esta palestra](https://github.com/melissawm/realworldscicomp/blob/master/melissa_qconsp_2019.pdf) da Melissa Weber (dep. de matemática da UFSC). Não sei se serve pra Keynote, mas creio que pelo menos serve divulgarmos o call for papers pra ela pedindo essa palestra.

**Comment by junakayama** [comment]
A Maria disse que tem interesse em participar, já peço pra ela um tema e falo o horário ou a gente espera ter mais palestrantes pra ver os detalhes?

**Comment by cauebs** [comment]
@junakayama Apoio. Acho que pode perguntar se ela tem ideia de tema e se tem preferência de horário.

**Comment by junakayama** [comment]
O que acham do tema "Uso de dados para impacto social"? Eu adorei, mas ela disse que pode ser voltado para negócios também

**Comment by JPTIZ** [comment]
Atualizei o post principal com quem já temos contato, temas (ao menos dos que eu sabia) e pra qual curso vai ser o foco.



> O que acham do tema "Uso de dados para impacto social"? Eu adorei, mas ela disse que pode ser voltado para negócios também

@junakayama Me parece um tema bem bacana, e ainda está dentro da área de SIN (já que, né, várias empresas fazem uso de dados de usuários e etc., BI está em ascenção, por aí vai).

**Comment by JPTIZ** [comment]
Atualizei de novo o post:
- Adicionei links para os Speakerfights;
- Consertei as quantidades nos checklists (antes tava a numeração levando em conta a programação antiga, sem as Keynotes).

@cauebs alguma resposta da Jéssica Temporal?

**Comment by junakayama** [comment]
## **Maria Queiroz**

**Título:**
Como usar dados para o bem?

**Horários de preferência:** 
Quarta ou Sexta 18h30

**Sobre ela:**:
Maria Queiroz é consultora de Business Intelligence e já atuou em grandes marcas do varejo como Adidas, Arezzo e Schutz. Já passou pelo setor de telecomunicações, setor público e indústria.
É apaixonada pelo poder dos dados para potencializar resultados,
seja ele para negócios ou para sociedade. 
Já mentorou grandes iniciativas de impacto social, como: Social Good Brasil, InovAtiva Brasil e Technovation Challenge.

![mariaqueiroz](https://user-images.githubusercontent.com/12129701/63512901-3d6d1c00-c4bb-11e9-813b-2c7e6fd0fb2e.jpg)

**Comment by junakayama** [comment]
## **Jean Hauck**

**Horários de preferência:**
30/09 (segunda) ou 01/10 (terça) às 20:20

**Título:** 
Modelagem ágil: integrando arquitetura e projeto a equipes ágeis

**Descrição**: 
"Sempre que membros da equipe discutem alternativas de solução técnica para as dores de um cliente, rabiscando ou não em um pedaço de papel, eles estão modelando! Modelagem de Software durante muito tempo foi confundida com documentação, e essa visão tem limitado as equipes no uso de técnicas que podem ajudar a solucionar problemas. Nesta palestra você conhecerá a Modelagem Ágil, seus fundamentos, valores, princípios e práticas de uma forma bem humorada e com exemplos práticos."

**Foto e Mini bio:**
Ele pediu para pegar no site dele
https://www.inf.ufsc.br/~jean.hauck/
Tirei algumas coisas para ficar com um tamanho aceitável.

"Jean Hauck é doutor em Engenharia do Conhecimento, com a área de pesquisa em Engenharia de Software e mestre em Ciência da Computação UFSC. Adquiriu experiência prática na indústria trabalhando em empresas brasileiras de software, iniciando na área de suporte ao usuário, passando por DBA, programador, analista de sistemas, arquiteto de software, gerente de projetos e diretor de P&D. Liderou projetos de desenvolvimento de software para grandes clientes, como: Santander, Banco do Brasil, HSBC, Oi e muitos outros. Com essa experiência adquirida, prestou consultorias e ministrou treinamentos nas áreas de Modelagem e Arquitetura de Software e de Melhoria de Processos de Software para grandes empresas, como: Samsung, WEG, Softplan e diversas outras. 
Em paralelo à sua atuação na indústria, foi também professor de Engenharia de Software na UNISUL e UNIVALI. Ministrou ainda diversas disciplinas em cursos de Pós-Graduação em Engenharia de Software na Unisul, Univali, Uniplac, Uniasselvi, Sociesc, Uniarp, Unidavi, Estácio e Esucri. Foii pesquisador visitante no Regulated Software Research Centre - Dundalk Institute of Technology - Irlanda. Atualmente é Professor Adjunto no INE da UFSC, pesquisador do Grupo de Qualidade de Software e vice-coordenador do curso de Sistemas de Informação/UFSC."

**Comment by junakayama** [comment]
## **Raul Wazlawick**

**Horário de preferência:**
não possui

**Título:**
Fazendo um bom projeto de pesquisa

**Apresentação:**
[Projeto de Pesquisa.pdf](https://github.com/seccom-ufsc/reunioes/files/3575892/Projeto.de.Pesquisa.pdf)

**Bio:**
Professor Titular em Ciência da Computação na UFSC, onde trabalha desde 1992. Possui Doutorado em Engenharia de Produção (UFSC, 1993) e Pós-Doutorado pela Universidade Nova de Lisboa (UNL, 1998). Na UFSC ocupou os seguintes cargos: Coordenador do Bacharelado em Ciência da Computação, Coordenador do Programa de Pós-Graduação (Mestrado) em Ciência da Computação, Conselheiro da Câmara de Pós-Graduação e Diretor Acadêmico do Campus de Araranguá. Na Sociedade Brasileira de Computação (SBC) foi Conselheiro Suplente por quatro mandatos e Conselheiro Titular por um mandato, além de Coordenador do Comitê Especial de Informática na Educação entre 1995 e 1997. Criou e foi editor da Revista Brasileira de Informática na Educação da SBC entre 1997 e 2001. Na International Federation for Information Processing (IFIP) foi representante do Brasil no Comitê Técnico de Educação (TC3) por 11 anos e Chair do Working Group on ICT and Higher Education (WG3.2) por 2 anos. No Ministério da Educação (MEC) foi membro do Comitê de Especialistas de Ensino em Ciência da Computação (CEEInf) por 4 anos e da Comissão Assessora da Área de Sistemas de Informação para o ENADE entre 2014 e 2016. É Coordenador Geral do Laboratório Bridge, com cerca de 120 colaboradores, que entre outros projetos desenvolve o sistema e-SUS AB, parceria da UFSC com o Ministério da Saúde para a reestruturação do sistema de informação da atenção básica (Postos de Saúde) no Brasil e o Sistema RNI (Registro Nacional de Implantes) em parceria com a ANVISA. Em 2013 recebeu o título de Professor Honoris Causa pelo Centro de Instrução de Guerra Eletrônica do Exército Brasileiro.

**Foto:**
![raul](https://user-images.githubusercontent.com/12129701/65543618-e3131100-dee7-11e9-85d8-411badf39c8c.png)

**Comment by junakayama** [comment]
## **Taíssa Vasconcelos** 

**Sobre ela:**

Taíssa Vasconcelos é uma belenense formada em Publicidade, que já atuou  como Social Media, Produtora, Visual Designer e Front-End. Tem várias especializações em Front e UX. Atualmente trabalha na Linx Impulse como Front-End. É apaixonada por animais, praia e acredita que vai ajudar a tornar o mundo um lugar melhor.

**Horário de preferência:**
Quinta ou sexta de noite

**Foto:**

![WhatsApp Image 2019-09-04 at 15 45 28](https://user-images.githubusercontent.com/12129701/64283962-e2add880-cf2e-11e9-936a-7aeb731adfbe.jpeg)

**Comment by Coquinho** [comment]
**Título**: Sistemas Multiagentes

**Resumo**:

Esta palestra trata a respeito de programação multiagente. Na palestra serão apresentados os conceitos básicos relacionados à programação orientada a agentes e multiagentes e suas motivações, assim como as principais diferenças entre programação orientada a agentes e multiagentes e outros paradigmas de programação. Serão também citadas algumas linguagens, competições, e aplicações relacionadas ao mundo dos agentes.

**Mini bio**:

Maicon Rafael Zatelli é atualmente professor do Departamento de Informática e Estatística da Universidade Federal de Florianópolis (UFSC). Possui mestrado e doutorado em Engenharia de Automação e Sistemas pela Universidade Federal de Santa Catarina (UFSC) (2013 e 2017, respectivamente), com período de doutorado sanduíche entre 2015 e 2016 pelo programa PDSE-CAPES na Universidade de Bolonha (Itália). Ambos, o doutorado e o mestrado, tiveram como área de pesquisa "sistemas multiagentes". Seus interesses de pesquisa atuais estão relacionados à sistemas multiagentes (em especial o desenvolvimento de ferramentas, plataformas, e linguagens para a programação de sistemas multiagentes e seus componentes), e à algoritmos e estruturas de dados (em especial a "teoria dos grafos", seus algoritmos e aplicações). Possui experiência e interesse em competições de programação, em especial a International Collegiate Programming Contest (ACM-ICPC) e Multi-Agent Programming Contest (MAPC).

**Foto**:

http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4384440U8
**Horário**: exceto na terça-feira pela manhã e à noite, qualquer outro dia/horário em princípio terei disponibilidade, visto que os horários que terei aulas estarei liberando os alunos para participarem do SECCOM. De qualquer forma, se preferir uma sugestão de horário, iria sugerir na quarta-feira a tarde (início da tarde) ou quinta-feira de manhã (início da manhã), visto que nesse período teria aula com a turma de paradigmas de programação, assim seria uma boa para cobrar presença deles. :) Apenas me avise com alguns dias de antecedência.

**Comment by JPTIZ** [comment]
Adicionei no post principal uma tabelinha com palestrantes + restrições de horários.

E na planilha de horários fui montando a alocação das palestras + keynotes [Numa planilha separada](https://docs.google.com/spreadsheets/d/1U_lRkZlp1PWaqAVPkdmxQygapAM8f2UH6FedAEp36XA/edit?pli=1#gid=476290658).

**Comment by JPTIZ** [comment]
Boa time, foi 10/10. Parabéns a todos.
